title: Masazumi Imai

theme: minima  # v2.5

header_pages:
  - index.md
  - publications.md
  - cv.md

author: Masazumi Imai

profile:
  name: Masazumi Imai
  avatar: assets/img/profile.png
  bio: "Ph.D. student at Tohoku University. Interested in Multi-Limbed Articulated Robots."
  email: imai.masazumi.p2@dc.tohoku.ac.jp
  location: Sendai, Japan
  github: MasazumiImai
  linkedin: masazumi-imai-1b403730a/
  google_scholar: https://scholar.google.co.jp/citations?user=xxxxxx
  researchgate: https://www.researchgate.net/profile/Masazumi-Imai
