title: Masazumi Imai

theme: minima  # v2.5

header_pages:
  - index.md
  - publications.md
  - cv.md

author: Masazumi Imai

profile:
  name: Masazumi Imai
  avatar: assets/img/profile.png
  bio: "Ph.D. student at Tohoku University. Interested in Multi-Limbed Articulated Robots."
  github: GitHub
  linkedin: LinkedIn
